name: CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  lint_backend:
    name: Lint Backend JS Files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run Linter
        run: |
          find ./giftlink-backend -name "*.js" -exec jshint {} +
          echo "Backend linting completed successfully."

  build_frontend:
    name: Build Frontend React App
    runs-on: ubuntu-latest
    needs: lint_backend
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: |
          cd giftlink-frontend
          npm install

      - name: Build Frontend
        run: |
          cd giftlink-frontend
          npm run build
          echo "Frontend build completed successfully."
